//! Asset metadata, matching the on-disk schema in `ARCHITECTURE.md`.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum License {
    CcBy,
    CcBySa,
    Cc0,
    Proprietary,
    Custom,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Vendor {
    pub id: String,
    pub name: String,
    pub url: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ThumbnailKind {
    /// PNG stored as base64-encoded bytes in the blob.
    Png,
    /// Placeholder generated by the pipeline (procedural).
    Placeholder,
}

/// One LOD blob: the actual mesh data is content-hashed and stored in the
/// `asset_blobs` table; `mesh_hash` is the lookup key.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MeshBlob {
    pub mesh_hash: String,
    pub vertex_count: u32,
    pub triangle_count: u32,
}

/// Asset metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AssetMetadata {
    pub asset_id: String,
    pub name: String,
    pub vendor: Vendor,
    pub version: String,
    pub license: License,
    pub attribution: Option<String>,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub style_tags: Vec<String>,
    pub lods: Vec<MeshBlob>,
    pub materials: Vec<String>,
    pub thumbnail_kind: ThumbnailKind,
    pub thumbnail_hash: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

impl AssetMetadata {
    pub fn new(
        asset_id: impl Into<String>,
        name: impl Into<String>,
        vendor: Vendor,
        version: impl Into<String>,
        license: License,
    ) -> Self {
        Self {
            asset_id: asset_id.into(),
            name: name.into(),
            vendor,
            version: version.into(),
            license,
            attribution: None,
            tags: Vec::new(),
            style_tags: Vec::new(),
            lods: Vec::new(),
            materials: Vec::new(),
            thumbnail_kind: ThumbnailKind::Placeholder,
            thumbnail_hash: String::new(),
            created_at: chrono::Utc::now(),
        }
    }
}
