//! R2004+ system section, file header, and page descriptors.
//!
//! Starting with R2004, AutoCAD replaced the flat section-locator
//! block with a "system section" that contains paged data. Each page
//! is independently compressed (LZ77-style) and CRC-32C-checked.
//! Pages are addressed via a page map (page id → file offset) and a
//! section map (logical section id → page id list).
//!
//! ```text
//! ┌───────────────────────────────────────────────────────────┐
//! │ 0x000 .. 0x080  Modern file header (signature, codepage…) │
//! │ 0x080 .. 0x0F8  R2004 file header (108 bytes encrypted +  │
//! │                  12 bytes pad), XOR-LCG keystream         │
//! │ 0x100 .. EOF    System section pages (LZ77-wrapped)       │
//! └───────────────────────────────────────────────────────────┘
//! ```
//!
//! The encryption is a one-time pad generated by a 32-bit LCG —
//! `seed * 0x343fd + 0x269ec3`, taking the high 16 bits of each
//! iteration as the pad byte. It's symmetric (encrypt and decrypt
//! are the same operation), exactly as documented in OpenDesign
//! § "R2004 file header — encryption" and reproduced in LibreDWG
//! `decrypt_R2004_header`.

use crate::dwg::bits::crc_32c;
use crate::dwg::error::{DwgError, DwgResult};
use crate::dwg::file::pages::{compress, decompress};

/// File offset of the encrypted R2004 file header.
pub const R2004_HEADER_OFFSET: usize = 0x80;
/// Size of the encrypted R2004 file header proper (no padding).
pub const R2004_HEADER_SIZE: usize = 108;
/// Trailing padding after the encrypted header. 12 bytes, also encrypted.
pub const R2004_HEADER_PADDING: usize = 12;
/// Offset of the CRC32 field within the decrypted R2004 file header.
pub const R2004_CRC32_OFFSET: usize = 0x68;
/// Size of the system-section page header (the leading metadata
/// preceding each compressed page payload).
pub const SYSTEM_PAGE_HEADER_SIZE: usize = 20;
/// Magic `section_type` for the section-page-map system page.
pub const SECTION_PAGE_MAP_MAGIC: u32 = 0x4163_0e3b;
/// Magic `section_type` for the section-info system page.
pub const SECTION_INFO_MAGIC: u32 = 0x4163_003b;

/// The 12-byte file_ID_string at the start of the decrypted header.
/// Used as a sentinel to detect decryption failure.
pub const R2004_FILE_ID_STRING: &[u8; 12] = b"AcFssFcAJMB\0";

/// Compression type stored in the system-page header. `0x02` means
/// "compressed via the LZ77 codec in [`crate::dwg::file::pages`]";
/// `0x01` means "stored as-is".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompressionType {
    Stored,
    Compressed,
}

impl CompressionType {
    pub fn as_u32(self) -> u32 {
        match self {
            CompressionType::Stored => 1,
            CompressionType::Compressed => 2,
        }
    }

    pub fn from_u32(v: u32) -> DwgResult<Self> {
        match v {
            1 => Ok(CompressionType::Stored),
            2 => Ok(CompressionType::Compressed),
            _ => Err(DwgError::InternalInvariant(format!(
                "R2004 system page: unknown compression_type {v}"
            ))),
        }
    }
}

/// The 0x6c-byte (= 108-byte) decrypted R2004 file header.
///
/// All fields are little-endian on disk. The CRC32 field is computed
/// over the first 0x6c bytes of the *decrypted* header with the CRC
/// field itself zeroed; encryption is applied afterwards.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct R2004FileHeader {
    /// Always `"AcFssFcAJMB\0"` after decryption.
    pub file_id_string: [u8; 12],
    pub header_address: u32,
    pub header_size: u32, // = 108
    pub x04: u32,         // = 4
    pub root_tree_node_gap: u32,
    pub lowermost_left_tree_node_gap: u32,
    pub lowermost_right_tree_node_gap: u32,
    pub unknown_long: u32, // = 1
    pub last_section_id: u32,
    pub last_section_address: u64,
    pub secondheader_address: u64,
    pub numgaps: u32,
    pub numsections: u32,
    pub x20: u32, // = 0x20
    pub x80: u32, // = 0x80
    pub x40: u32, // = 0x40
    pub section_map_id: u32,
    pub section_map_address: u64,
    pub section_info_id: i32,
    pub section_array_size: u32,
    pub gap_array_size: u32,
    pub crc32: u32,
}

impl R2004FileHeader {
    /// Construct a defaults-populated header. Caller still has to
    /// patch the addresses / ids / sizes for their specific file
    /// layout, then call [`Self::encode_encrypted`] to serialize.
    pub fn new() -> Self {
        Self {
            file_id_string: *R2004_FILE_ID_STRING,
            header_size: 108,
            x04: 4,
            unknown_long: 1,
            x20: 0x20,
            x80: 0x80,
            x40: 0x40,
            ..Self::default()
        }
    }

    /// Read 108 bytes of plaintext (post-decryption) and parse them.
    pub fn from_decrypted(plain: &[u8]) -> DwgResult<Self> {
        if plain.len() < R2004_HEADER_SIZE {
            return Err(DwgError::UnexpectedEof {
                byte: plain.len(),
                bit: 0,
            });
        }
        let mut file_id_string = [0u8; 12];
        file_id_string.copy_from_slice(&plain[0..12]);
        if file_id_string != *R2004_FILE_ID_STRING {
            return Err(DwgError::InternalInvariant(format!(
                "R2004 file header: decryption sentinel mismatch (got {file_id_string:02x?}, \
                 expected AcFssFcAJMB)"
            )));
        }
        let hdr = Self {
            file_id_string,
            header_address: read_u32(plain, 0x0c),
            header_size: read_u32(plain, 0x10),
            x04: read_u32(plain, 0x14),
            root_tree_node_gap: read_u32(plain, 0x18),
            lowermost_left_tree_node_gap: read_u32(plain, 0x1c),
            lowermost_right_tree_node_gap: read_u32(plain, 0x20),
            unknown_long: read_u32(plain, 0x24),
            last_section_id: read_u32(plain, 0x28),
            last_section_address: read_u64(plain, 0x2c),
            secondheader_address: read_u64(plain, 0x34),
            numgaps: read_u32(plain, 0x3c),
            numsections: read_u32(plain, 0x40),
            x20: read_u32(plain, 0x44),
            x80: read_u32(plain, 0x48),
            x40: read_u32(plain, 0x4c),
            section_map_id: read_u32(plain, 0x50),
            section_map_address: read_u64(plain, 0x54),
            section_info_id: read_u32(plain, 0x5c) as i32,
            section_array_size: read_u32(plain, 0x60),
            gap_array_size: read_u32(plain, 0x64),
            crc32: read_u32(plain, 0x68),
        };
        // Verify the CRC32 (LE bytes, computed over the header with the
        // crc32 field zeroed). LibreDWG only warns on mismatch; we
        // return a hard error so corruption is surfaced rather than
        // silently propagated.
        let mut crc_buf = plain[..R2004_CRC32_OFFSET + 4].to_vec();
        for byte in &mut crc_buf[R2004_CRC32_OFFSET..R2004_CRC32_OFFSET + 4] {
            *byte = 0;
        }
        let calc = crc_32c(0, &crc_buf);
        if calc != hdr.crc32 {
            return Err(DwgError::SectionCrcMismatch {
                section: "r2004_file_header",
                computed: calc,
                stored: hdr.crc32,
            });
        }
        Ok(hdr)
    }

    /// Serialize as encrypted bytes (108 + 12 padding = 120 bytes
    /// total). CRC32 is recomputed from the freshly encoded layout, so
    /// callers can leave [`Self::crc32`] at zero before calling.
    pub fn encode_encrypted(&self) -> Vec<u8> {
        let mut plain = vec![0u8; R2004_HEADER_SIZE + R2004_HEADER_PADDING];
        plain[0..12].copy_from_slice(&self.file_id_string);
        write_u32(&mut plain, 0x0c, self.header_address);
        write_u32(&mut plain, 0x10, self.header_size);
        write_u32(&mut plain, 0x14, self.x04);
        write_u32(&mut plain, 0x18, self.root_tree_node_gap);
        write_u32(&mut plain, 0x1c, self.lowermost_left_tree_node_gap);
        write_u32(&mut plain, 0x20, self.lowermost_right_tree_node_gap);
        write_u32(&mut plain, 0x24, self.unknown_long);
        write_u32(&mut plain, 0x28, self.last_section_id);
        write_u64(&mut plain, 0x2c, self.last_section_address);
        write_u64(&mut plain, 0x34, self.secondheader_address);
        write_u32(&mut plain, 0x3c, self.numgaps);
        write_u32(&mut plain, 0x40, self.numsections);
        write_u32(&mut plain, 0x44, self.x20);
        write_u32(&mut plain, 0x48, self.x80);
        write_u32(&mut plain, 0x4c, self.x40);
        write_u32(&mut plain, 0x50, self.section_map_id);
        write_u64(&mut plain, 0x54, self.section_map_address);
        write_u32(&mut plain, 0x5c, self.section_info_id as u32);
        write_u32(&mut plain, 0x60, self.section_array_size);
        write_u32(&mut plain, 0x64, self.gap_array_size);
        // CRC32 zeroed before computation.
        write_u32(&mut plain, 0x68, 0);
        let crc = crc_32c(0, &plain[..R2004_CRC32_OFFSET + 4]);
        write_u32(&mut plain, 0x68, crc);
        // Padding stays as zeros — it gets encrypted along with the
        // rest. The leading 12 bytes of the next page header
        // (comp_data_size etc.) overlap with the padding region; the
        // caller is responsible for preserving those bytes by passing
        // them in via [`encrypt_lcg_inplace`] *after* this encode.
        encrypt_lcg_inplace(&mut plain);
        plain
    }
}

/// Apply the R2004 LCG XOR keystream in place. Symmetric — calling
/// this twice on the same buffer yields the original bytes.
///
/// Algorithm (verbatim from OpenDesign / LibreDWG):
///
/// ```text
/// rseed = 1
/// for each byte:
///     rseed = rseed * 0x343fd + 0x269ec3 (mod 2^32)
///     pad   = (rseed >> 16) & 0xff
///     buf[i] ^= pad
/// ```
pub fn encrypt_lcg_inplace(buf: &mut [u8]) {
    let mut rseed: u32 = 1;
    for byte in buf.iter_mut() {
        rseed = rseed.wrapping_mul(0x0003_43fd).wrapping_add(0x0026_9ec3);
        let pad = (rseed >> 16) as u8;
        *byte ^= pad;
    }
}

/// The 20-byte header that precedes each compressed payload in the
/// R2004 system section. Total system page on disk = header + payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SystemPageHeader {
    /// Identifies what kind of map/info this page contains. See
    /// [`SECTION_PAGE_MAP_MAGIC`] / [`SECTION_INFO_MAGIC`].
    pub section_type: u32,
    /// Decompressed size of the payload.
    pub decomp_data_size: u32,
    /// On-disk size of the payload (after compression, including LZ77
    /// framing).
    pub comp_data_size: u32,
    /// `1 = stored`, `2 = LZ77 compressed`.
    pub compression_type: u32,
    /// CRC-32C over the first 20 bytes (with `checksum` zeroed) seeded
    /// by the checksum of the *compressed* payload. See the LibreDWG
    /// helper `dwg_section_page_checksum` for the exact ordering.
    pub checksum: u32,
}

impl SystemPageHeader {
    pub fn encode(&self) -> [u8; SYSTEM_PAGE_HEADER_SIZE] {
        let mut buf = [0u8; SYSTEM_PAGE_HEADER_SIZE];
        buf[0..4].copy_from_slice(&self.section_type.to_le_bytes());
        buf[4..8].copy_from_slice(&self.decomp_data_size.to_le_bytes());
        buf[8..12].copy_from_slice(&self.comp_data_size.to_le_bytes());
        buf[12..16].copy_from_slice(&self.compression_type.to_le_bytes());
        buf[16..20].copy_from_slice(&self.checksum.to_le_bytes());
        buf
    }

    pub fn parse(bytes: &[u8]) -> DwgResult<Self> {
        if bytes.len() < SYSTEM_PAGE_HEADER_SIZE {
            return Err(DwgError::UnexpectedEof {
                byte: bytes.len(),
                bit: 0,
            });
        }
        Ok(Self {
            section_type: read_u32(bytes, 0),
            decomp_data_size: read_u32(bytes, 4),
            comp_data_size: read_u32(bytes, 8),
            compression_type: read_u32(bytes, 12),
            checksum: read_u32(bytes, 16),
        })
    }
}

/// Compute the page checksum the way LibreDWG `dwg_section_page_checksum`
/// does — two passes of CRC-32C: first over a header with the checksum
/// field zeroed (20 bytes), then chained over the (compressed) payload.
pub fn system_page_checksum(header: SystemPageHeader, payload: &[u8]) -> u32 {
    let mut header_with_zero_checksum = header;
    header_with_zero_checksum.checksum = 0;
    let header_bytes = header_with_zero_checksum.encode();
    let seed = crc_32c(0, &header_bytes);
    crc_32c(seed, payload)
}

/// Wrap a logical system-section payload (decompressed) as the
/// on-disk page: 20-byte header + LZ77-compressed payload + CRC-32C
/// chained checksum. Returns the bytes ready to be written at the
/// page's file offset.
pub fn write_system_page(
    section_type: u32,
    decomp_payload: &[u8],
    compression: CompressionType,
) -> DwgResult<Vec<u8>> {
    let payload = match compression {
        CompressionType::Stored => decomp_payload.to_vec(),
        CompressionType::Compressed => compress(decomp_payload)?,
    };
    let mut header = SystemPageHeader {
        section_type,
        decomp_data_size: decomp_payload.len() as u32,
        comp_data_size: payload.len() as u32,
        compression_type: compression.as_u32(),
        checksum: 0,
    };
    header.checksum = system_page_checksum(header, &payload);
    let mut buf = Vec::with_capacity(SYSTEM_PAGE_HEADER_SIZE + payload.len());
    buf.extend_from_slice(&header.encode());
    buf.extend_from_slice(&payload);
    Ok(buf)
}

/// Read one system-section page back out and return its logical
/// payload. Verifies the checksum and decompresses if needed.
pub fn read_system_page(bytes: &[u8]) -> DwgResult<(SystemPageHeader, Vec<u8>)> {
    let header = SystemPageHeader::parse(bytes)?;
    let comp_len = header.comp_data_size as usize;
    if bytes.len() < SYSTEM_PAGE_HEADER_SIZE + comp_len {
        return Err(DwgError::UnexpectedEof {
            byte: bytes.len(),
            bit: 0,
        });
    }
    let payload = &bytes[SYSTEM_PAGE_HEADER_SIZE..SYSTEM_PAGE_HEADER_SIZE + comp_len];
    let calc = system_page_checksum(
        SystemPageHeader {
            checksum: 0,
            ..header
        },
        payload,
    );
    if calc != header.checksum {
        return Err(DwgError::SectionCrcMismatch {
            section: "r2004_system_page",
            computed: calc,
            stored: header.checksum,
        });
    }
    let compression = CompressionType::from_u32(header.compression_type)?;
    let plain = match compression {
        CompressionType::Stored => payload.to_vec(),
        CompressionType::Compressed => decompress(payload, header.decomp_data_size as usize)?,
    };
    Ok((header, plain))
}

/// A single page descriptor inside the R2004+ page map.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PageDescriptor {
    pub page_id: i32,
    pub page_size: u32,
    pub file_offset: u64,
}

/// A logical section made up of one or more pages.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SectionDescriptor {
    pub section_id: u64,
    pub name: String,
    pub max_decompressed_size: u64,
    pub encoding: SectionEncoding,
    pub pages: Vec<i32>,
}

/// How a section's pages are stored on disk.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SectionEncoding {
    /// Raw (uncompressed) pages.
    Raw,
    /// LZ77-style compressed pages (R2004+).
    Compressed,
    /// Encrypted with the magic-byte XOR mask (R2018 handle pages).
    Encrypted,
}

/// Serialize the page-map payload: a sequence of (page_id, page_size)
/// records, byte-packed (page_id is RLd, page_size is RL). The actual
/// file_offset is implicit (cumulative). The on-disk format is
/// documented in OpenDesign § "System section — page map".
pub fn encode_page_map(pages: &[PageDescriptor]) -> Vec<u8> {
    let mut buf = Vec::with_capacity(pages.len() * 8);
    for p in pages {
        buf.extend_from_slice(&p.page_id.to_le_bytes());
        buf.extend_from_slice(&p.page_size.to_le_bytes());
    }
    buf
}

/// Inverse of [`encode_page_map`]: parse (page_id, page_size)
/// records. Requires `file_start` so the cumulative file_offset can
/// be derived for each page (each page starts immediately after the
/// previous one).
pub fn decode_page_map(buf: &[u8], file_start: u64) -> DwgResult<Vec<PageDescriptor>> {
    if buf.len() % 8 != 0 {
        return Err(DwgError::InternalInvariant(format!(
            "R2004 page map length {} not divisible by 8",
            buf.len()
        )));
    }
    let mut out = Vec::with_capacity(buf.len() / 8);
    let mut cursor = file_start;
    for chunk in buf.chunks_exact(8) {
        let page_id = i32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
        let page_size = u32::from_le_bytes([chunk[4], chunk[5], chunk[6], chunk[7]]);
        out.push(PageDescriptor {
            page_id,
            page_size,
            file_offset: cursor,
        });
        cursor += page_size as u64;
    }
    Ok(out)
}

fn read_u32(b: &[u8], at: usize) -> u32 {
    u32::from_le_bytes([b[at], b[at + 1], b[at + 2], b[at + 3]])
}

fn read_u64(b: &[u8], at: usize) -> u64 {
    u64::from_le_bytes([
        b[at],
        b[at + 1],
        b[at + 2],
        b[at + 3],
        b[at + 4],
        b[at + 5],
        b[at + 6],
        b[at + 7],
    ])
}

fn write_u32(b: &mut [u8], at: usize, v: u32) {
    b[at..at + 4].copy_from_slice(&v.to_le_bytes());
}

fn write_u64(b: &mut [u8], at: usize, v: u64) {
    b[at..at + 8].copy_from_slice(&v.to_le_bytes());
}

/// Convenience reader for legacy callers that expected the
/// previously-stub `parse_descriptors` API. Returns the structured
/// error from the inner system-section reader.
pub fn parse_descriptors(
    _bytes: &[u8],
) -> DwgResult<(Vec<PageDescriptor>, Vec<SectionDescriptor>)> {
    // Full traversal is wired in alongside the R2004+ reader
    // integration in a follow-up commit. For now, callers that need
    // the descriptors should compose [`read_system_page`] +
    // [`decode_page_map`] directly — this top-level convenience is
    // gated on the R2004 reader so it returns a structured error if
    // invoked before the dispatch path is in place.
    Err(DwgError::UnsupportedInVersion {
        version: crate::dwg::version::Version::R2004,
        what: "system-section traversal is delivered alongside R2004+ entity \
               codec wiring; compose read_system_page + decode_page_map \
               directly until then"
            .into(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lcg_is_involutive() {
        let original = b"R2004 file header padding scratch buffer 12345678".to_vec();
        let mut buf = original.clone();
        encrypt_lcg_inplace(&mut buf);
        assert_ne!(buf, original);
        encrypt_lcg_inplace(&mut buf);
        assert_eq!(buf, original);
    }

    #[test]
    fn lcg_first_byte_matches_libredwg_reference() {
        // rseed_1 = 1 * 0x343fd + 0x269ec3 = 0x269ec3 + 0x343fd = 0x29e2c0.
        // pad_1   = (rseed_1 >> 16) & 0xff = 0x29.
        let mut buf = [0u8; 1];
        encrypt_lcg_inplace(&mut buf);
        assert_eq!(buf[0], 0x29);
    }

    #[test]
    fn lcg_first_12_bytes_match_libredwg_published_ciphertext() {
        // LibreDWG `encode.c` documents: "AcFssFcAJMB" plaintext
        // encrypts to bytes 68 40 F8 F7 92 2A B5 EF 18 DD 0B F1.
        let mut buf = [0u8; 12];
        buf.copy_from_slice(b"AcFssFcAJMB\0");
        encrypt_lcg_inplace(&mut buf);
        assert_eq!(
            buf,
            [0x68, 0x40, 0xF8, 0xF7, 0x92, 0x2A, 0xB5, 0xEF, 0x18, 0xDD, 0x0B, 0xF1]
        );
    }

    #[test]
    fn r2004_header_round_trips_through_encrypted_form() {
        let mut hdr = R2004FileHeader::new();
        hdr.header_address = 0x100;
        hdr.section_map_address = 0x97a0;
        hdr.section_map_id = 0x13;
        hdr.numsections = 17;
        hdr.section_array_size = 19;
        hdr.last_section_address = 0x9c80;
        hdr.last_section_id = 0x13;
        hdr.secondheader_address = 0x984b;
        let encrypted = hdr.encode_encrypted();
        // The first 12 bytes after encryption must match the
        // libredwg-published constant (the file_id_string encrypts to a
        // known fingerprint that AutoCAD uses to verify decryption).
        assert_eq!(
            &encrypted[0..12],
            &[0x68, 0x40, 0xF8, 0xF7, 0x92, 0x2A, 0xB5, 0xEF, 0x18, 0xDD, 0x0B, 0xF1]
        );
        // Decrypt and parse.
        let mut plain = encrypted.clone();
        encrypt_lcg_inplace(&mut plain);
        let parsed = R2004FileHeader::from_decrypted(&plain).unwrap();
        // The encoder computes and patches crc32 from the freshly
        // serialized bytes; the original `hdr` had crc32 == 0 by
        // default. Cross-check every other field directly, and then
        // verify the recomputed crc32 matches what's now stored.
        let mut hdr_with_crc = hdr.clone();
        hdr_with_crc.crc32 = parsed.crc32;
        assert_eq!(parsed, hdr_with_crc);
        // Sanity-check that the recomputed CRC is non-zero (i.e. the
        // encoder actually patched it rather than leaving it at the
        // sentinel value).
        assert_ne!(parsed.crc32, 0);
    }

    #[test]
    fn r2004_header_rejects_decryption_sentinel_mismatch() {
        let mut plain = vec![0u8; R2004_HEADER_SIZE];
        plain[..12].copy_from_slice(b"NotAcFssFcAJ");
        let err = R2004FileHeader::from_decrypted(&plain).unwrap_err();
        assert!(matches!(err, DwgError::InternalInvariant(_)));
    }

    #[test]
    fn r2004_header_rejects_crc_mismatch() {
        let hdr = R2004FileHeader::new();
        let encrypted = hdr.encode_encrypted();
        let mut plain = encrypted.clone();
        encrypt_lcg_inplace(&mut plain);
        // Corrupt one byte before the CRC.
        plain[0x10] ^= 0xff;
        let err = R2004FileHeader::from_decrypted(&plain).unwrap_err();
        assert!(matches!(err, DwgError::SectionCrcMismatch { .. }));
    }

    #[test]
    fn system_page_round_trips_compressed() {
        let payload: Vec<u8> = (0..512).map(|i| (i & 0xff) as u8).collect();
        let on_disk = write_system_page(
            SECTION_PAGE_MAP_MAGIC,
            &payload,
            CompressionType::Compressed,
        )
        .unwrap();
        let (header, decoded) = read_system_page(&on_disk).unwrap();
        assert_eq!(header.section_type, SECTION_PAGE_MAP_MAGIC);
        assert_eq!(header.decomp_data_size as usize, payload.len());
        assert_eq!(decoded, payload);
    }

    #[test]
    fn system_page_round_trips_stored() {
        let payload = b"page contents that do not compress".to_vec();
        let on_disk =
            write_system_page(SECTION_INFO_MAGIC, &payload, CompressionType::Stored).unwrap();
        let (header, decoded) = read_system_page(&on_disk).unwrap();
        assert_eq!(header.compression_type, CompressionType::Stored.as_u32());
        assert_eq!(decoded, payload);
    }

    #[test]
    fn system_page_detects_checksum_corruption() {
        let payload = b"checksum-corruption-test payload bytes here".to_vec();
        let mut on_disk =
            write_system_page(SECTION_INFO_MAGIC, &payload, CompressionType::Stored).unwrap();
        // Corrupt the first payload byte; checksum should now fail.
        on_disk[SYSTEM_PAGE_HEADER_SIZE] ^= 0xff;
        let err = read_system_page(&on_disk).unwrap_err();
        assert!(matches!(err, DwgError::SectionCrcMismatch { .. }));
    }

    #[test]
    fn page_map_round_trip() {
        let pages = vec![
            PageDescriptor {
                page_id: 1,
                page_size: 0x2000,
                file_offset: 0x100,
            },
            PageDescriptor {
                page_id: 2,
                page_size: 0x1000,
                file_offset: 0x2100,
            },
            PageDescriptor {
                page_id: 3,
                page_size: 0x400,
                file_offset: 0x3100,
            },
        ];
        let encoded = encode_page_map(&pages);
        let decoded = decode_page_map(&encoded, 0x100).unwrap();
        assert_eq!(decoded, pages);
    }

    #[test]
    fn page_map_rejects_truncated_input() {
        let buf = vec![0u8; 9]; // not a multiple of 8
        let err = decode_page_map(&buf, 0x100).unwrap_err();
        assert!(matches!(err, DwgError::InternalInvariant(_)));
    }

    #[test]
    fn parse_descriptors_returns_unsupported() {
        let err = parse_descriptors(&[]).unwrap_err();
        assert!(matches!(err, DwgError::UnsupportedInVersion { .. }));
    }
}
