//! R2004+ system section, file header, and page descriptors.
//!
//! Starting with R2004, AutoCAD replaced the flat section-locator
//! block with a "system section" that contains paged data. Each page
//! is independently compressed (LZ77-style) and CRC-32C-checked.
//! Pages are addressed via a page map (page id → file offset) and a
//! section map (logical section id → page id list).
//!
//! ```text
//! ┌───────────────────────────────────────────────────────────┐
//! │ 0x000 .. 0x080  Modern file header (signature, codepage…) │
//! │ 0x080 .. 0x0F8  R2004 file header (108 bytes encrypted +  │
//! │                  12 bytes pad), XOR-LCG keystream         │
//! │ 0x100 .. EOF    System section pages (LZ77-wrapped)       │
//! └───────────────────────────────────────────────────────────┘
//! ```
//!
//! The encryption is a one-time pad generated by a 32-bit LCG —
//! `seed * 0x343fd + 0x269ec3`, taking the high 16 bits of each
//! iteration as the pad byte. It's symmetric (encrypt and decrypt
//! are the same operation), exactly as documented in OpenDesign
//! § "R2004 file header — encryption" and reproduced in LibreDWG
//! `decrypt_R2004_header`.

use crate::dwg::bits::{crc_32_ieee, crc_32c};
use crate::dwg::error::{DwgError, DwgResult};
use crate::dwg::file::pages::{compress, decompress};

/// File offset of the encrypted R2004 file header.
pub const R2004_HEADER_OFFSET: usize = 0x80;
/// Size of the encrypted R2004 file header proper (no padding).
pub const R2004_HEADER_SIZE: usize = 108;
/// Trailing padding after the encrypted header. 12 bytes, also encrypted.
pub const R2004_HEADER_PADDING: usize = 12;
/// Offset of the CRC32 field within the decrypted R2004 file header.
pub const R2004_CRC32_OFFSET: usize = 0x68;
/// Size of the system-section page header (the leading metadata
/// preceding each compressed page payload).
pub const SYSTEM_PAGE_HEADER_SIZE: usize = 20;
/// Magic `section_type` for the section-page-map system page.
pub const SECTION_PAGE_MAP_MAGIC: u32 = 0x4163_0e3b;
/// Magic `section_type` for the section-info system page.
pub const SECTION_INFO_MAGIC: u32 = 0x4163_003b;

/// The 12-byte file_ID_string at the start of the decrypted header.
/// Used as a sentinel to detect decryption failure.
pub const R2004_FILE_ID_STRING: &[u8; 12] = b"AcFssFcAJMB\0";

/// Compression type stored in the system-page header. `0x02` means
/// "compressed via the LZ77 codec in [`crate::dwg::file::pages`]";
/// `0x01` means "stored as-is".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompressionType {
    Stored,
    Compressed,
}

impl CompressionType {
    pub fn as_u32(self) -> u32 {
        match self {
            CompressionType::Stored => 1,
            CompressionType::Compressed => 2,
        }
    }

    pub fn from_u32(v: u32) -> DwgResult<Self> {
        match v {
            1 => Ok(CompressionType::Stored),
            2 => Ok(CompressionType::Compressed),
            _ => Err(DwgError::InternalInvariant(format!(
                "R2004 system page: unknown compression_type {v}"
            ))),
        }
    }
}

/// The 0x6c-byte (= 108-byte) decrypted R2004 file header.
///
/// All fields are little-endian on disk. The CRC32 field is computed
/// over the first 0x6c bytes of the *decrypted* header with the CRC
/// field itself zeroed; encryption is applied afterwards.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct R2004FileHeader {
    /// Always `"AcFssFcAJMB\0"` after decryption.
    pub file_id_string: [u8; 12],
    pub header_address: u32,
    pub header_size: u32, // = 108
    pub x04: u32,         // = 4
    pub root_tree_node_gap: u32,
    pub lowermost_left_tree_node_gap: u32,
    pub lowermost_right_tree_node_gap: u32,
    pub unknown_long: u32, // = 1
    pub last_section_id: u32,
    pub last_section_address: u64,
    pub secondheader_address: u64,
    pub numgaps: u32,
    pub numsections: u32,
    pub x20: u32, // = 0x20
    pub x80: u32, // = 0x80
    pub x40: u32, // = 0x40
    pub section_map_id: u32,
    pub section_map_address: u64,
    pub section_info_id: i32,
    pub section_array_size: u32,
    pub gap_array_size: u32,
    pub crc32: u32,
}

impl R2004FileHeader {
    /// Construct a defaults-populated header. Caller still has to
    /// patch the addresses / ids / sizes for their specific file
    /// layout, then call [`Self::encode_encrypted`] to serialize.
    pub fn new() -> Self {
        Self {
            file_id_string: *R2004_FILE_ID_STRING,
            header_size: 108,
            x04: 4,
            unknown_long: 1,
            x20: 0x20,
            x80: 0x80,
            x40: 0x40,
            ..Self::default()
        }
    }

    /// Read 108 bytes of plaintext (post-decryption) and parse them.
    pub fn from_decrypted(plain: &[u8]) -> DwgResult<Self> {
        if plain.len() < R2004_HEADER_SIZE {
            return Err(DwgError::UnexpectedEof {
                byte: plain.len(),
                bit: 0,
            });
        }
        let mut file_id_string = [0u8; 12];
        file_id_string.copy_from_slice(&plain[0..12]);
        if file_id_string != *R2004_FILE_ID_STRING {
            return Err(DwgError::InternalInvariant(format!(
                "R2004 file header: decryption sentinel mismatch (got {file_id_string:02x?}, \
                 expected AcFssFcAJMB)"
            )));
        }
        let hdr = Self {
            file_id_string,
            header_address: read_u32(plain, 0x0c),
            header_size: read_u32(plain, 0x10),
            x04: read_u32(plain, 0x14),
            root_tree_node_gap: read_u32(plain, 0x18),
            lowermost_left_tree_node_gap: read_u32(plain, 0x1c),
            lowermost_right_tree_node_gap: read_u32(plain, 0x20),
            unknown_long: read_u32(plain, 0x24),
            last_section_id: read_u32(plain, 0x28),
            last_section_address: read_u64(plain, 0x2c),
            secondheader_address: read_u64(plain, 0x34),
            numgaps: read_u32(plain, 0x3c),
            numsections: read_u32(plain, 0x40),
            x20: read_u32(plain, 0x44),
            x80: read_u32(plain, 0x48),
            x40: read_u32(plain, 0x4c),
            section_map_id: read_u32(plain, 0x50),
            section_map_address: read_u64(plain, 0x54),
            section_info_id: read_u32(plain, 0x5c) as i32,
            section_array_size: read_u32(plain, 0x60),
            gap_array_size: read_u32(plain, 0x64),
            crc32: read_u32(plain, 0x68),
        };
        // Verify the CRC32 (LE bytes, computed over the header with the
        // crc32 field zeroed). LibreDWG uses standard CRC-32 IEEE (its
        // `bit_calc_CRC32`), NOT the Castagnoli variant used for the
        // section page checksums — distinct polynomials, distinct
        // tables. LibreDWG only warns on mismatch; we return a hard
        // error so corruption is surfaced rather than silently
        // propagated.
        let mut crc_buf = plain[..R2004_CRC32_OFFSET + 4].to_vec();
        for byte in &mut crc_buf[R2004_CRC32_OFFSET..R2004_CRC32_OFFSET + 4] {
            *byte = 0;
        }
        let calc = crc_32_ieee(0, &crc_buf);
        if calc != hdr.crc32 {
            return Err(DwgError::SectionCrcMismatch {
                section: "r2004_file_header",
                computed: calc,
                stored: hdr.crc32,
            });
        }
        Ok(hdr)
    }

    /// Serialize as encrypted bytes (108 + 12 padding = 120 bytes
    /// total). CRC32 is recomputed from the freshly encoded layout, so
    /// callers can leave [`Self::crc32`] at zero before calling.
    pub fn encode_encrypted(&self) -> Vec<u8> {
        let mut plain = vec![0u8; R2004_HEADER_SIZE + R2004_HEADER_PADDING];
        plain[0..12].copy_from_slice(&self.file_id_string);
        write_u32(&mut plain, 0x0c, self.header_address);
        write_u32(&mut plain, 0x10, self.header_size);
        write_u32(&mut plain, 0x14, self.x04);
        write_u32(&mut plain, 0x18, self.root_tree_node_gap);
        write_u32(&mut plain, 0x1c, self.lowermost_left_tree_node_gap);
        write_u32(&mut plain, 0x20, self.lowermost_right_tree_node_gap);
        write_u32(&mut plain, 0x24, self.unknown_long);
        write_u32(&mut plain, 0x28, self.last_section_id);
        write_u64(&mut plain, 0x2c, self.last_section_address);
        write_u64(&mut plain, 0x34, self.secondheader_address);
        write_u32(&mut plain, 0x3c, self.numgaps);
        write_u32(&mut plain, 0x40, self.numsections);
        write_u32(&mut plain, 0x44, self.x20);
        write_u32(&mut plain, 0x48, self.x80);
        write_u32(&mut plain, 0x4c, self.x40);
        write_u32(&mut plain, 0x50, self.section_map_id);
        write_u64(&mut plain, 0x54, self.section_map_address);
        write_u32(&mut plain, 0x5c, self.section_info_id as u32);
        write_u32(&mut plain, 0x60, self.section_array_size);
        write_u32(&mut plain, 0x64, self.gap_array_size);
        // CRC32 zeroed before computation. LibreDWG uses the standard
        // IEEE CRC-32 here (its `bit_calc_CRC32`); the CRC-32C variant
        // used by the page-level checksum is a different algorithm.
        write_u32(&mut plain, 0x68, 0);
        let crc = crc_32_ieee(0, &plain[..R2004_CRC32_OFFSET + 4]);
        write_u32(&mut plain, 0x68, crc);
        // Padding stays as zeros — it gets encrypted along with the
        // rest. The leading 12 bytes of the next page header
        // (comp_data_size etc.) overlap with the padding region; the
        // caller is responsible for preserving those bytes by passing
        // them in via [`encrypt_lcg_inplace`] *after* this encode.
        encrypt_lcg_inplace(&mut plain);
        plain
    }
}

/// Apply the R2004 LCG XOR keystream in place. Symmetric — calling
/// this twice on the same buffer yields the original bytes.
///
/// Algorithm (verbatim from OpenDesign / LibreDWG):
///
/// ```text
/// rseed = 1
/// for each byte:
///     rseed = rseed * 0x343fd + 0x269ec3 (mod 2^32)
///     pad   = (rseed >> 16) & 0xff
///     buf[i] ^= pad
/// ```
pub fn encrypt_lcg_inplace(buf: &mut [u8]) {
    let mut rseed: u32 = 1;
    for byte in buf.iter_mut() {
        rseed = rseed.wrapping_mul(0x0003_43fd).wrapping_add(0x0026_9ec3);
        let pad = (rseed >> 16) as u8;
        *byte ^= pad;
    }
}

/// The 20-byte header that precedes each compressed payload in the
/// R2004 system section. Total system page on disk = header + payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SystemPageHeader {
    /// Identifies what kind of map/info this page contains. See
    /// [`SECTION_PAGE_MAP_MAGIC`] / [`SECTION_INFO_MAGIC`].
    pub section_type: u32,
    /// Decompressed size of the payload.
    pub decomp_data_size: u32,
    /// On-disk size of the payload (after compression, including LZ77
    /// framing).
    pub comp_data_size: u32,
    /// `1 = stored`, `2 = LZ77 compressed`.
    pub compression_type: u32,
    /// CRC-32C over the first 20 bytes (with `checksum` zeroed) seeded
    /// by the checksum of the *compressed* payload. See the LibreDWG
    /// helper `dwg_section_page_checksum` for the exact ordering.
    pub checksum: u32,
}

impl SystemPageHeader {
    pub fn encode(&self) -> [u8; SYSTEM_PAGE_HEADER_SIZE] {
        let mut buf = [0u8; SYSTEM_PAGE_HEADER_SIZE];
        buf[0..4].copy_from_slice(&self.section_type.to_le_bytes());
        buf[4..8].copy_from_slice(&self.decomp_data_size.to_le_bytes());
        buf[8..12].copy_from_slice(&self.comp_data_size.to_le_bytes());
        buf[12..16].copy_from_slice(&self.compression_type.to_le_bytes());
        buf[16..20].copy_from_slice(&self.checksum.to_le_bytes());
        buf
    }

    pub fn parse(bytes: &[u8]) -> DwgResult<Self> {
        if bytes.len() < SYSTEM_PAGE_HEADER_SIZE {
            return Err(DwgError::UnexpectedEof {
                byte: bytes.len(),
                bit: 0,
            });
        }
        Ok(Self {
            section_type: read_u32(bytes, 0),
            decomp_data_size: read_u32(bytes, 4),
            comp_data_size: read_u32(bytes, 8),
            compression_type: read_u32(bytes, 12),
            checksum: read_u32(bytes, 16),
        })
    }
}

/// Compute the page checksum the way LibreDWG `dwg_section_page_checksum`
/// does — two passes of CRC-32C: first over a header with the checksum
/// field zeroed (20 bytes), then chained over the (compressed) payload.
pub fn system_page_checksum(header: SystemPageHeader, payload: &[u8]) -> u32 {
    let mut header_with_zero_checksum = header;
    header_with_zero_checksum.checksum = 0;
    let header_bytes = header_with_zero_checksum.encode();
    let seed = crc_32c(0, &header_bytes);
    crc_32c(seed, payload)
}

/// Wrap a logical system-section payload (decompressed) as the
/// on-disk page: 20-byte header + (optionally encrypted)
/// LZ77-compressed payload + CRC-32C chained checksum. Returns the
/// bytes ready to be written at the page's file offset.
///
/// The `encrypted` flag is the per-section flag from
/// [`SectionInfoDescriptor::encrypted`]: when set, the
/// (compressed) payload is XORed with the R2018 magic-byte mask
/// before the checksum is computed. The checksum is computed over
/// the encrypted bytes so the page can be validated without first
/// decrypting.
pub fn write_system_page(
    section_type: u32,
    decomp_payload: &[u8],
    compression: CompressionType,
    encrypted: bool,
) -> DwgResult<Vec<u8>> {
    let mut payload = match compression {
        CompressionType::Stored => decomp_payload.to_vec(),
        CompressionType::Compressed => compress(decomp_payload)?,
    };
    if encrypted {
        crate::dwg::file::pages::xor_decrypt_handle_page(&mut payload, 0);
    }
    let mut header = SystemPageHeader {
        section_type,
        decomp_data_size: decomp_payload.len() as u32,
        comp_data_size: payload.len() as u32,
        compression_type: compression.as_u32(),
        checksum: 0,
    };
    header.checksum = system_page_checksum(header, &payload);
    let mut buf = Vec::with_capacity(SYSTEM_PAGE_HEADER_SIZE + payload.len());
    buf.extend_from_slice(&header.encode());
    buf.extend_from_slice(&payload);
    Ok(buf)
}

/// Read one system-section page back out and return its logical
/// payload. Verifies the checksum, decrypts (if `encrypted`), and
/// decompresses if needed.
///
/// The checksum is computed over the encrypted-and-compressed payload
/// (the same way it was on write), so we validate before decrypting.
pub fn read_system_page(bytes: &[u8], encrypted: bool) -> DwgResult<(SystemPageHeader, Vec<u8>)> {
    let header = SystemPageHeader::parse(bytes)?;
    let comp_len = header.comp_data_size as usize;
    if bytes.len() < SYSTEM_PAGE_HEADER_SIZE + comp_len {
        return Err(DwgError::UnexpectedEof {
            byte: bytes.len(),
            bit: 0,
        });
    }
    let payload_slice = &bytes[SYSTEM_PAGE_HEADER_SIZE..SYSTEM_PAGE_HEADER_SIZE + comp_len];
    let calc = system_page_checksum(
        SystemPageHeader {
            checksum: 0,
            ..header
        },
        payload_slice,
    );
    if calc != header.checksum {
        return Err(DwgError::SectionCrcMismatch {
            section: "r2004_system_page",
            computed: calc,
            stored: header.checksum,
        });
    }
    // XOR is involutive, so we can decrypt in-place by XORing again
    // with the same key. Copy first so we don't disturb the caller's
    // buffer.
    let mut payload = payload_slice.to_vec();
    if encrypted {
        crate::dwg::file::pages::xor_decrypt_handle_page(&mut payload, 0);
    }
    let compression = CompressionType::from_u32(header.compression_type)?;
    let plain = match compression {
        CompressionType::Stored => payload,
        CompressionType::Compressed => decompress(&payload, header.decomp_data_size as usize)?,
    };
    Ok((header, plain))
}

/// Size of the data-page header (the encrypted preamble that
/// precedes every data section page — Header, Classes, Objects,
/// Handles, etc.).
pub const DATA_PAGE_HEADER_SIZE: usize = 32;
/// Magic constant identifying a data-section page in its decrypted
/// page header. Always `0x4163043b`; differs from the page-map
/// magic ([`SECTION_PAGE_MAP_MAGIC`]) and the section-info magic
/// ([`SECTION_INFO_MAGIC`]).
pub const DATA_PAGE_MAGIC: u32 = 0x4163_043b;
/// XOR mask base used to encrypt data-page headers. The actual
/// per-page mask is `DATA_PAGE_MASK ^ page_file_offset` (as u32);
/// see LibreDWG encode.c line 4222.
pub const DATA_PAGE_MASK: u32 = 0x4164_536b;

/// The 32-byte clear-text data-page header, before XOR-encryption.
///
/// LibreDWG layout (`src/decode.c` struct around line 1943,
/// `src/encode.c` line 4193):
///
/// | Offset | Field                | Notes                                  |
/// |-------:|----------------------|----------------------------------------|
/// |   0x00 | `page_type`          | Always `DATA_PAGE_MAGIC` (`0x4163043b`)|
/// |   0x04 | `section_type`       | Section-type id (1=Header, 3=Classes, 4=Handles, 7=Objects, …) |
/// |   0x08 | `data_size`          | Compressed bytes on disk (= raw count when stored uncompressed) |
/// |   0x0c | `page_size`          | Decompressed bytes                     |
/// |   0x10 | `start_offset`       | Offset in the decompressed section where this page's bytes live (multi-page sections only) |
/// |   0x14 | `unknown`            | Always 0                               |
/// |   0x18 | `page_header_crc`    | CRC over the header with this field zeroed, seeded by `data_crc` |
/// |   0x1c | `data_crc`           | CRC over the (compressed) data bytes   |
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DataPageHeader {
    pub page_type: u32,
    pub section_type: u32,
    pub data_size: u32,
    pub page_size: u32,
    pub start_offset: u32,
    pub unknown: u32,
    pub page_header_crc: u32,
    pub data_crc: u32,
}

impl DataPageHeader {
    pub fn encode(&self) -> [u8; DATA_PAGE_HEADER_SIZE] {
        let mut buf = [0u8; DATA_PAGE_HEADER_SIZE];
        buf[0x00..0x04].copy_from_slice(&self.page_type.to_le_bytes());
        buf[0x04..0x08].copy_from_slice(&self.section_type.to_le_bytes());
        buf[0x08..0x0c].copy_from_slice(&self.data_size.to_le_bytes());
        buf[0x0c..0x10].copy_from_slice(&self.page_size.to_le_bytes());
        buf[0x10..0x14].copy_from_slice(&self.start_offset.to_le_bytes());
        buf[0x14..0x18].copy_from_slice(&self.unknown.to_le_bytes());
        buf[0x18..0x1c].copy_from_slice(&self.page_header_crc.to_le_bytes());
        buf[0x1c..0x20].copy_from_slice(&self.data_crc.to_le_bytes());
        buf
    }

    pub fn parse(bytes: &[u8]) -> DwgResult<Self> {
        if bytes.len() < DATA_PAGE_HEADER_SIZE {
            return Err(DwgError::UnexpectedEof {
                byte: bytes.len(),
                bit: 0,
            });
        }
        Ok(Self {
            page_type: read_u32(bytes, 0x00),
            section_type: read_u32(bytes, 0x04),
            data_size: read_u32(bytes, 0x08),
            page_size: read_u32(bytes, 0x0c),
            start_offset: read_u32(bytes, 0x10),
            unknown: read_u32(bytes, 0x14),
            page_header_crc: read_u32(bytes, 0x18),
            data_crc: read_u32(bytes, 0x1c),
        })
    }
}

/// XOR-encrypt or decrypt a 32-byte data-page header in place. The
/// mask is `DATA_PAGE_MASK ^ page_file_offset`, applied to every
/// 4-byte little-endian word. Symmetric: calling this twice with the
/// same `page_file_offset` recovers the original bytes.
pub fn xor_data_page_header(buf: &mut [u8; DATA_PAGE_HEADER_SIZE], page_file_offset: u64) {
    let mask = DATA_PAGE_MASK ^ (page_file_offset as u32);
    for word in buf.chunks_exact_mut(4) {
        let v = u32::from_le_bytes([word[0], word[1], word[2], word[3]]);
        let masked = v ^ mask;
        word.copy_from_slice(&masked.to_le_bytes());
    }
}

/// Wrap a logical (decompressed) data-section payload as the on-disk
/// page: 32-byte encrypted header + raw payload. Used for R2004+
/// data sections (Header, Classes, Objects, Handles, …) — NOT for
/// the system-section pages (page-map and section-info) which use
/// [`write_system_page`].
///
/// We deliberately store the payload uncompressed (LibreDWG does the
/// same on the encode side; the on-disk format permits it because
/// the page header carries explicit `data_size == page_size` and the
/// reader detects this case as "stored, no LZ77 frame to parse").
pub fn write_data_page(
    section_type: u32,
    decomp_payload: &[u8],
    start_offset: u32,
    page_file_offset: u64,
) -> Vec<u8> {
    let data_size = decomp_payload.len() as u32;
    // CRC over the data bytes (seed 0); LibreDWG's
    // `dwg_section_page_checksum` is CRC-32C with reflected output
    // and final inversion — same as our [`crc_32c`] helper.
    let data_crc = crc_32c(0, decomp_payload);
    let mut header = DataPageHeader {
        page_type: DATA_PAGE_MAGIC,
        section_type,
        data_size,
        page_size: data_size,
        start_offset,
        unknown: 0,
        page_header_crc: 0,
        data_crc,
    };
    // Compute the header CRC over the cleartext header with the CRC
    // field zeroed, seeded by `data_crc` (LibreDWG encode.c:4218).
    let hdr_bytes_for_crc = header.encode();
    let page_hdr_crc = crc_32c(data_crc, &hdr_bytes_for_crc);
    header.page_header_crc = page_hdr_crc;
    let mut encrypted = header.encode();
    xor_data_page_header(&mut encrypted, page_file_offset);

    let mut out = Vec::with_capacity(DATA_PAGE_HEADER_SIZE + decomp_payload.len());
    out.extend_from_slice(&encrypted);
    out.extend_from_slice(decomp_payload);
    out
}

/// Inverse of [`write_data_page`]: decrypt the 32-byte header at
/// `page_file_offset`, validate both CRCs, and return the
/// (decrypted) header + a reference to the raw payload bytes.
pub fn read_data_page(
    page_bytes: &[u8],
    page_file_offset: u64,
) -> DwgResult<(DataPageHeader, &[u8])> {
    if page_bytes.len() < DATA_PAGE_HEADER_SIZE {
        return Err(DwgError::UnexpectedEof {
            byte: page_bytes.len(),
            bit: 0,
        });
    }
    let mut hdr_buf = [0u8; DATA_PAGE_HEADER_SIZE];
    hdr_buf.copy_from_slice(&page_bytes[..DATA_PAGE_HEADER_SIZE]);
    xor_data_page_header(&mut hdr_buf, page_file_offset);
    let header = DataPageHeader::parse(&hdr_buf)?;
    if header.page_type != DATA_PAGE_MAGIC {
        return Err(DwgError::InternalInvariant(format!(
            "R2004 data page at offset {page_file_offset:#x}: page_type {:#x} != {:#x}",
            header.page_type, DATA_PAGE_MAGIC
        )));
    }
    let data_len = header.data_size as usize;
    if page_bytes.len() < DATA_PAGE_HEADER_SIZE + data_len {
        return Err(DwgError::UnexpectedEof {
            byte: page_bytes.len(),
            bit: 0,
        });
    }
    let payload = &page_bytes[DATA_PAGE_HEADER_SIZE..DATA_PAGE_HEADER_SIZE + data_len];
    // Recompute and validate the data CRC.
    let calc_data = crc_32c(0, payload);
    if calc_data != header.data_crc {
        return Err(DwgError::SectionCrcMismatch {
            section: "r2004_data_page_data",
            computed: calc_data,
            stored: header.data_crc,
        });
    }
    // Recompute and validate the page-header CRC.
    let mut hdr_for_crc = header;
    hdr_for_crc.page_header_crc = 0;
    let calc_hdr = crc_32c(calc_data, &hdr_for_crc.encode());
    if calc_hdr != header.page_header_crc {
        return Err(DwgError::SectionCrcMismatch {
            section: "r2004_data_page_header",
            computed: calc_hdr,
            stored: header.page_header_crc,
        });
    }
    Ok((header, payload))
}

/// A single page descriptor inside the R2004+ page map.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PageDescriptor {
    pub page_id: i32,
    pub page_size: u32,
    pub file_offset: u64,
}

/// A logical section made up of one or more pages.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SectionDescriptor {
    pub section_id: u64,
    pub name: String,
    pub max_decompressed_size: u64,
    pub encoding: SectionEncoding,
    pub pages: Vec<i32>,
}

/// How a section's pages are stored on disk.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SectionEncoding {
    /// Raw (uncompressed) pages.
    Raw,
    /// LZ77-style compressed pages (R2004+).
    Compressed,
    /// Encrypted with the magic-byte XOR mask (R2018 handle pages).
    Encrypted,
}

/// Serialize the page-map payload: a sequence of (page_id, page_size)
/// records, byte-packed (page_id is RLd, page_size is RL). The actual
/// file_offset is implicit (cumulative). The on-disk format is
/// documented in OpenDesign § "System section — page map".
pub fn encode_page_map(pages: &[PageDescriptor]) -> Vec<u8> {
    let mut buf = Vec::with_capacity(pages.len() * 8);
    for p in pages {
        buf.extend_from_slice(&p.page_id.to_le_bytes());
        buf.extend_from_slice(&p.page_size.to_le_bytes());
    }
    buf
}

/// Inverse of [`encode_page_map`]: parse (page_id, page_size)
/// records. Requires `file_start` so the cumulative file_offset can
/// be derived for each page (each page starts immediately after the
/// previous one).
pub fn decode_page_map(buf: &[u8], file_start: u64) -> DwgResult<Vec<PageDescriptor>> {
    if buf.len() % 8 != 0 {
        return Err(DwgError::InternalInvariant(format!(
            "R2004 page map length {} not divisible by 8",
            buf.len()
        )));
    }
    let mut out = Vec::with_capacity(buf.len() / 8);
    let mut cursor = file_start;
    for chunk in buf.chunks_exact(8) {
        let page_id = i32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
        let page_size = u32::from_le_bytes([chunk[4], chunk[5], chunk[6], chunk[7]]);
        out.push(PageDescriptor {
            page_id,
            page_size,
            file_offset: cursor,
        });
        cursor += page_size as u64;
    }
    Ok(out)
}

fn read_u32(b: &[u8], at: usize) -> u32 {
    u32::from_le_bytes([b[at], b[at + 1], b[at + 2], b[at + 3]])
}

fn read_u64(b: &[u8], at: usize) -> u64 {
    u64::from_le_bytes([
        b[at],
        b[at + 1],
        b[at + 2],
        b[at + 3],
        b[at + 4],
        b[at + 5],
        b[at + 6],
        b[at + 7],
    ])
}

fn write_u32(b: &mut [u8], at: usize, v: u32) {
    b[at..at + 4].copy_from_slice(&v.to_le_bytes());
}

fn write_u64(b: &mut [u8], at: usize, v: u64) {
    b[at..at + 8].copy_from_slice(&v.to_le_bytes());
}

/// The 20-byte preamble at the start of the section-info system page.
/// Describes how many section descriptors follow and the global
/// encryption / compression posture of the file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct SectionInfoHeader {
    /// Number of section descriptors that follow this preamble.
    pub num_desc: u32,
    /// Per-spec name "compressed": always `2` (LZ77) on AutoCAD-written
    /// files; LibreDWG keeps it verbatim for round-trip fidelity.
    pub compressed: u32,
    /// Maximum decompressed size of any single page in the file. Almost
    /// always `0x7400`; legal up to `0x8000`.
    pub max_size: u32,
    /// `0` = unencrypted file, `1` = encrypted (rare on consumer
    /// files), `2` = the R2018 magic-XOR handle-page encryption.
    pub encrypted: u32,
    /// Duplicate of `num_desc` — always equal on well-formed files.
    pub num_desc2: u32,
}

impl SectionInfoHeader {
    pub fn encode(&self) -> [u8; 20] {
        let mut buf = [0u8; 20];
        buf[0..4].copy_from_slice(&self.num_desc.to_le_bytes());
        buf[4..8].copy_from_slice(&self.compressed.to_le_bytes());
        buf[8..12].copy_from_slice(&self.max_size.to_le_bytes());
        buf[12..16].copy_from_slice(&self.encrypted.to_le_bytes());
        buf[16..20].copy_from_slice(&self.num_desc2.to_le_bytes());
        buf
    }

    pub fn parse(bytes: &[u8]) -> DwgResult<Self> {
        if bytes.len() < 20 {
            return Err(DwgError::UnexpectedEof {
                byte: bytes.len(),
                bit: 0,
            });
        }
        Ok(Self {
            num_desc: read_u32(bytes, 0),
            compressed: read_u32(bytes, 4),
            max_size: read_u32(bytes, 8),
            encrypted: read_u32(bytes, 12),
            num_desc2: read_u32(bytes, 16),
        })
    }
}

/// A single page entry within a [`SectionInfoDescriptor`]. The
/// `address` is the absolute file offset of the page on disk.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct SectionInfoPage {
    pub page_number: i32,
    /// Compressed (on-disk) size of this page's payload.
    pub comp_size: u32,
    pub address: u64,
}

/// One logical section's full descriptor — the variable-sized
/// 92 + 16 × num_pages record that follows [`SectionInfoHeader`] in
/// the section-info system page.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SectionInfoDescriptor {
    /// Total decompressed size of this section, summed across all
    /// pages.
    pub size: u64,
    /// Maximum decompressed size of any single page in this section.
    /// Typically `0x7400`.
    pub max_decomp_size: u32,
    /// `1` = stored, `2` = LZ77-compressed.
    pub compressed: u32,
    /// Section type opaque tag (AutoCAD uses these to disambiguate
    /// duplicate names — we preserve them verbatim).
    pub type_tag: u32,
    /// `0` = unencrypted, `1` = encrypted, `2` = R2018 magic-XOR.
    pub encrypted: u32,
    /// Verbatim 64-byte name field. ASCII bytes followed by trailing
    /// NULs. Names like `"AcDb:Header"`, `"AcDb:Classes"`,
    /// `"AcDb:Handles"`, `"AcDb:AcDbObjects"`.
    pub name: [u8; 64],
    /// Opaque `unknown` slot (reserved by the spec — preserved
    /// verbatim for round-trip fidelity).
    pub unknown: u32,
    /// Pages that compose this section, in on-disk order.
    pub pages: Vec<SectionInfoPage>,
}

impl Default for SectionInfoDescriptor {
    fn default() -> Self {
        Self {
            size: 0,
            max_decomp_size: 0x7400,
            compressed: 2,
            type_tag: 0,
            encrypted: 0,
            name: [0u8; 64],
            unknown: 0,
            pages: Vec::new(),
        }
    }
}

impl SectionInfoDescriptor {
    /// Construct from an ASCII section name. Pads the 64-byte name
    /// field with trailing NULs. Panics if the input is longer than
    /// 64 bytes — the names AutoCAD uses are all <= 32 chars so this
    /// is enforced as a programming-error contract.
    pub fn with_name(name: &str) -> Self {
        assert!(name.len() <= 64, "section name too long: {name:?}");
        let mut name_buf = [0u8; 64];
        name_buf[..name.len()].copy_from_slice(name.as_bytes());
        Self {
            name: name_buf,
            ..Self::default()
        }
    }

    /// Extract the printable ASCII portion of the name field (drops
    /// trailing NULs and any non-ASCII bytes).
    pub fn name_str(&self) -> &str {
        let end = self.name.iter().position(|&b| b == 0).unwrap_or(64);
        std::str::from_utf8(&self.name[..end]).unwrap_or("")
    }

    /// Total on-disk size of this descriptor when serialized:
    /// 96 fixed bytes + 16 × `pages.len()` page records.
    pub fn encoded_size(&self) -> usize {
        96 + 16 * self.pages.len()
    }
}

/// Serialize a header + descriptors into the on-disk system-info
/// payload (the decompressed bytes that go into the LZ77 wrapper).
pub fn encode_section_info(
    header: SectionInfoHeader,
    descriptors: &[SectionInfoDescriptor],
) -> Vec<u8> {
    let mut buf = Vec::with_capacity(
        20 + descriptors
            .iter()
            .map(SectionInfoDescriptor::encoded_size)
            .sum::<usize>(),
    );
    buf.extend_from_slice(&header.encode());
    for d in descriptors {
        buf.extend_from_slice(&d.size.to_le_bytes());
        buf.extend_from_slice(&(d.pages.len() as u32).to_le_bytes());
        buf.extend_from_slice(&d.max_decomp_size.to_le_bytes());
        buf.extend_from_slice(&d.unknown.to_le_bytes());
        buf.extend_from_slice(&d.compressed.to_le_bytes());
        buf.extend_from_slice(&d.type_tag.to_le_bytes());
        buf.extend_from_slice(&d.encrypted.to_le_bytes());
        buf.extend_from_slice(&d.name);
        for p in &d.pages {
            buf.extend_from_slice(&p.page_number.to_le_bytes());
            buf.extend_from_slice(&p.comp_size.to_le_bytes());
            buf.extend_from_slice(&p.address.to_le_bytes());
        }
    }
    buf
}

/// Inverse of [`encode_section_info`].
pub fn decode_section_info(
    bytes: &[u8],
) -> DwgResult<(SectionInfoHeader, Vec<SectionInfoDescriptor>)> {
    let header = SectionInfoHeader::parse(bytes)?;
    let mut cursor = 20usize;
    let mut descriptors = Vec::with_capacity(header.num_desc as usize);
    for i in 0..header.num_desc {
        if cursor + 96 > bytes.len() {
            return Err(DwgError::InternalInvariant(format!(
                "R2004 section_info: truncated at descriptor {i} (need {} got {})",
                cursor + 96,
                bytes.len()
            )));
        }
        let size = read_u64(bytes, cursor);
        let num_sections = read_u32(bytes, cursor + 8);
        let max_decomp_size = read_u32(bytes, cursor + 12);
        let unknown = read_u32(bytes, cursor + 16);
        let compressed = read_u32(bytes, cursor + 20);
        let type_tag = read_u32(bytes, cursor + 24);
        let encrypted = read_u32(bytes, cursor + 28);
        let mut name = [0u8; 64];
        name.copy_from_slice(&bytes[cursor + 32..cursor + 96]);
        cursor += 96;

        let need = num_sections as usize * 16;
        if cursor + need > bytes.len() {
            return Err(DwgError::InternalInvariant(format!(
                "R2004 section_info[{i}]: truncated page list (need {} got {})",
                cursor + need,
                bytes.len()
            )));
        }
        let mut pages = Vec::with_capacity(num_sections as usize);
        for _ in 0..num_sections {
            let page_number = i32::from_le_bytes([
                bytes[cursor],
                bytes[cursor + 1],
                bytes[cursor + 2],
                bytes[cursor + 3],
            ]);
            let comp_size = read_u32(bytes, cursor + 4);
            let address = read_u64(bytes, cursor + 8);
            pages.push(SectionInfoPage {
                page_number,
                comp_size,
                address,
            });
            cursor += 16;
        }
        descriptors.push(SectionInfoDescriptor {
            size,
            max_decomp_size,
            compressed,
            type_tag,
            encrypted,
            name,
            unknown,
            pages,
        });
    }
    Ok((header, descriptors))
}

/// Convenience reader for legacy callers that expected the
/// previously-stub `parse_descriptors` API. Returns the structured
/// error from the inner system-section reader.
pub fn parse_descriptors(
    _bytes: &[u8],
) -> DwgResult<(Vec<PageDescriptor>, Vec<SectionDescriptor>)> {
    // Full traversal is wired in alongside the R2004+ reader
    // integration in a follow-up commit. For now, callers that need
    // the descriptors should compose [`read_system_page`] +
    // [`decode_page_map`] directly — this top-level convenience is
    // gated on the R2004 reader so it returns a structured error if
    // invoked before the dispatch path is in place.
    Err(DwgError::UnsupportedInVersion {
        version: crate::dwg::version::Version::R2004,
        what: "system-section traversal is delivered alongside R2004+ entity \
               codec wiring; compose read_system_page + decode_page_map \
               directly until then"
            .into(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lcg_is_involutive() {
        let original = b"R2004 file header padding scratch buffer 12345678".to_vec();
        let mut buf = original.clone();
        encrypt_lcg_inplace(&mut buf);
        assert_ne!(buf, original);
        encrypt_lcg_inplace(&mut buf);
        assert_eq!(buf, original);
    }

    #[test]
    fn lcg_first_byte_matches_libredwg_reference() {
        // rseed_1 = 1 * 0x343fd + 0x269ec3 = 0x269ec3 + 0x343fd = 0x29e2c0.
        // pad_1   = (rseed_1 >> 16) & 0xff = 0x29.
        let mut buf = [0u8; 1];
        encrypt_lcg_inplace(&mut buf);
        assert_eq!(buf[0], 0x29);
    }

    #[test]
    fn lcg_first_12_bytes_match_libredwg_published_ciphertext() {
        // LibreDWG `encode.c` documents: "AcFssFcAJMB" plaintext
        // encrypts to bytes 68 40 F8 F7 92 2A B5 EF 18 DD 0B F1.
        let mut buf = [0u8; 12];
        buf.copy_from_slice(b"AcFssFcAJMB\0");
        encrypt_lcg_inplace(&mut buf);
        assert_eq!(
            buf,
            [0x68, 0x40, 0xF8, 0xF7, 0x92, 0x2A, 0xB5, 0xEF, 0x18, 0xDD, 0x0B, 0xF1]
        );
    }

    #[test]
    fn r2004_header_round_trips_through_encrypted_form() {
        let mut hdr = R2004FileHeader::new();
        hdr.header_address = 0x100;
        hdr.section_map_address = 0x97a0;
        hdr.section_map_id = 0x13;
        hdr.numsections = 17;
        hdr.section_array_size = 19;
        hdr.last_section_address = 0x9c80;
        hdr.last_section_id = 0x13;
        hdr.secondheader_address = 0x984b;
        let encrypted = hdr.encode_encrypted();
        // The first 12 bytes after encryption must match the
        // libredwg-published constant (the file_id_string encrypts to a
        // known fingerprint that AutoCAD uses to verify decryption).
        assert_eq!(
            &encrypted[0..12],
            &[0x68, 0x40, 0xF8, 0xF7, 0x92, 0x2A, 0xB5, 0xEF, 0x18, 0xDD, 0x0B, 0xF1]
        );
        // Decrypt and parse.
        let mut plain = encrypted.clone();
        encrypt_lcg_inplace(&mut plain);
        let parsed = R2004FileHeader::from_decrypted(&plain).unwrap();
        // The encoder computes and patches crc32 from the freshly
        // serialized bytes; the original `hdr` had crc32 == 0 by
        // default. Cross-check every other field directly, and then
        // verify the recomputed crc32 matches what's now stored.
        let mut hdr_with_crc = hdr.clone();
        hdr_with_crc.crc32 = parsed.crc32;
        assert_eq!(parsed, hdr_with_crc);
        // Sanity-check that the recomputed CRC is non-zero (i.e. the
        // encoder actually patched it rather than leaving it at the
        // sentinel value).
        assert_ne!(parsed.crc32, 0);
    }

    #[test]
    fn r2004_header_rejects_decryption_sentinel_mismatch() {
        let mut plain = vec![0u8; R2004_HEADER_SIZE];
        plain[..12].copy_from_slice(b"NotAcFssFcAJ");
        let err = R2004FileHeader::from_decrypted(&plain).unwrap_err();
        assert!(matches!(err, DwgError::InternalInvariant(_)));
    }

    #[test]
    fn r2004_header_rejects_crc_mismatch() {
        let hdr = R2004FileHeader::new();
        let encrypted = hdr.encode_encrypted();
        let mut plain = encrypted.clone();
        encrypt_lcg_inplace(&mut plain);
        // Corrupt one byte before the CRC.
        plain[0x10] ^= 0xff;
        let err = R2004FileHeader::from_decrypted(&plain).unwrap_err();
        assert!(matches!(err, DwgError::SectionCrcMismatch { .. }));
    }

    #[test]
    fn system_page_round_trips_compressed() {
        let payload: Vec<u8> = (0..512).map(|i| (i & 0xff) as u8).collect();
        let on_disk = write_system_page(
            SECTION_PAGE_MAP_MAGIC,
            &payload,
            CompressionType::Compressed,
            false,
        )
        .unwrap();
        let (header, decoded) = read_system_page(&on_disk, false).unwrap();
        assert_eq!(header.section_type, SECTION_PAGE_MAP_MAGIC);
        assert_eq!(header.decomp_data_size as usize, payload.len());
        assert_eq!(decoded, payload);
    }

    #[test]
    fn system_page_round_trips_stored() {
        let payload = b"page contents that do not compress".to_vec();
        let on_disk =
            write_system_page(SECTION_INFO_MAGIC, &payload, CompressionType::Stored, false)
                .unwrap();
        let (header, decoded) = read_system_page(&on_disk, false).unwrap();
        assert_eq!(header.compression_type, CompressionType::Stored.as_u32());
        assert_eq!(decoded, payload);
    }

    #[test]
    fn system_page_detects_checksum_corruption() {
        let payload = b"checksum-corruption-test payload bytes here".to_vec();
        let mut on_disk =
            write_system_page(SECTION_INFO_MAGIC, &payload, CompressionType::Stored, false)
                .unwrap();
        // Corrupt the first payload byte; checksum should now fail.
        on_disk[SYSTEM_PAGE_HEADER_SIZE] ^= 0xff;
        let err = read_system_page(&on_disk, false).unwrap_err();
        assert!(matches!(err, DwgError::SectionCrcMismatch { .. }));
    }

    #[test]
    fn encrypted_system_page_round_trips_compressed() {
        // R2018 handle-page emulation: an LZ77-compressed payload
        // XORed with the magic-byte mask. Must round-trip via the
        // matching encrypted=true on read.
        let payload: Vec<u8> = (0..1024).map(|i| (i & 0xff) as u8).collect();
        let on_disk = write_system_page(
            SECTION_PAGE_MAP_MAGIC,
            &payload,
            CompressionType::Compressed,
            true,
        )
        .unwrap();
        let (header, decoded) = read_system_page(&on_disk, true).unwrap();
        assert_eq!(header.section_type, SECTION_PAGE_MAP_MAGIC);
        assert_eq!(decoded, payload);
    }

    #[test]
    fn encrypted_system_page_differs_from_plain_one() {
        // Two pages written with the same payload but different
        // encrypted flags must differ in their on-disk bytes —
        // confirms the XOR is actually applied.
        let payload: Vec<u8> = (0..256).map(|i| (i & 0xff) as u8).collect();
        let plain = write_system_page(SECTION_INFO_MAGIC, &payload, CompressionType::Stored, false)
            .unwrap();
        let encrypted =
            write_system_page(SECTION_INFO_MAGIC, &payload, CompressionType::Stored, true).unwrap();
        assert_ne!(
            &plain[SYSTEM_PAGE_HEADER_SIZE..],
            &encrypted[SYSTEM_PAGE_HEADER_SIZE..]
        );
    }

    #[test]
    fn page_map_round_trip() {
        let pages = vec![
            PageDescriptor {
                page_id: 1,
                page_size: 0x2000,
                file_offset: 0x100,
            },
            PageDescriptor {
                page_id: 2,
                page_size: 0x1000,
                file_offset: 0x2100,
            },
            PageDescriptor {
                page_id: 3,
                page_size: 0x400,
                file_offset: 0x3100,
            },
        ];
        let encoded = encode_page_map(&pages);
        let decoded = decode_page_map(&encoded, 0x100).unwrap();
        assert_eq!(decoded, pages);
    }

    #[test]
    fn page_map_rejects_truncated_input() {
        let buf = vec![0u8; 9]; // not a multiple of 8
        let err = decode_page_map(&buf, 0x100).unwrap_err();
        assert!(matches!(err, DwgError::InternalInvariant(_)));
    }

    #[test]
    fn parse_descriptors_returns_unsupported() {
        let err = parse_descriptors(&[]).unwrap_err();
        assert!(matches!(err, DwgError::UnsupportedInVersion { .. }));
    }

    #[test]
    fn section_info_round_trip() {
        let header = SectionInfoHeader {
            num_desc: 4,
            compressed: 2,
            max_size: 0x7400,
            encrypted: 0,
            num_desc2: 4,
        };
        let descriptors = vec![
            {
                let mut d = SectionInfoDescriptor::with_name("AcDb:Header");
                d.size = 0x1234;
                d.type_tag = 1;
                d.pages = vec![SectionInfoPage {
                    page_number: 1,
                    comp_size: 0x500,
                    address: 0x100,
                }];
                d
            },
            {
                let mut d = SectionInfoDescriptor::with_name("AcDb:Classes");
                d.size = 0x2345;
                d.type_tag = 2;
                d.pages = vec![SectionInfoPage {
                    page_number: 2,
                    comp_size: 0x800,
                    address: 0x600,
                }];
                d
            },
            {
                let mut d = SectionInfoDescriptor::with_name("AcDb:Handles");
                d.size = 0x3456;
                d.type_tag = 3;
                d.pages = vec![
                    SectionInfoPage {
                        page_number: 3,
                        comp_size: 0x1000,
                        address: 0xe00,
                    },
                    SectionInfoPage {
                        page_number: 4,
                        comp_size: 0x800,
                        address: 0x1e00,
                    },
                ];
                d
            },
            {
                let mut d = SectionInfoDescriptor::with_name("AcDb:AcDbObjects");
                d.size = 0x4567;
                d.type_tag = 4;
                d.pages = vec![SectionInfoPage {
                    page_number: 5,
                    comp_size: 0x2000,
                    address: 0x2600,
                }];
                d
            },
        ];
        let buf = encode_section_info(header, &descriptors);
        // Expected size: 20 byte header + 96 base * 4 sections + 16 * (1+1+2+1)
        // = 20 + 384 + 80 = 484 bytes.
        assert_eq!(buf.len(), 20 + 96 * 4 + 16 * 5);
        let (parsed_header, parsed_descriptors) = decode_section_info(&buf).unwrap();
        assert_eq!(parsed_header, header);
        assert_eq!(parsed_descriptors, descriptors);
    }

    #[test]
    fn section_info_name_round_trips_through_64_byte_field() {
        let d = SectionInfoDescriptor::with_name("AcDb:Header");
        assert_eq!(d.name_str(), "AcDb:Header");
        // Trailing bytes after the ASCII content must be NUL-padded.
        assert!(d.name[11..].iter().all(|&b| b == 0));
    }

    #[test]
    fn section_info_descriptor_encoded_size_includes_pages() {
        let mut d = SectionInfoDescriptor::with_name("AcDb:Test");
        assert_eq!(d.encoded_size(), 96);
        d.pages.push(SectionInfoPage::default());
        assert_eq!(d.encoded_size(), 96 + 16);
        d.pages.push(SectionInfoPage::default());
        assert_eq!(d.encoded_size(), 96 + 32);
    }

    #[test]
    fn section_info_rejects_truncated_descriptor() {
        let header = SectionInfoHeader {
            num_desc: 1,
            compressed: 2,
            max_size: 0x7400,
            encrypted: 0,
            num_desc2: 1,
        };
        // Truncate everything after the header — 20 bytes is < the
        // 96-byte descriptor preamble we promised in the header.
        let buf = header.encode();
        let err = decode_section_info(&buf).unwrap_err();
        assert!(matches!(err, DwgError::InternalInvariant(_)));
    }

    #[test]
    fn section_info_rejects_truncated_page_list() {
        // Header says 1 descriptor with 2 pages, but we only supply 1
        // page's worth of bytes after the 96-byte preamble.
        let header = SectionInfoHeader {
            num_desc: 1,
            compressed: 2,
            max_size: 0x7400,
            encrypted: 0,
            num_desc2: 1,
        };
        let mut d = SectionInfoDescriptor::with_name("AcDb:Test");
        d.pages = vec![SectionInfoPage::default(), SectionInfoPage::default()];
        let mut buf = encode_section_info(header, &[d.clone()]);
        // Drop the trailing 16 bytes (one page's worth).
        buf.truncate(buf.len() - 16);
        let err = decode_section_info(&buf).unwrap_err();
        assert!(matches!(err, DwgError::InternalInvariant(_)));
    }
}
