//! Image-gen sidecar process management.
//!
//! Spawns the configured image-gen server binary (today
//! [`stable-diffusion.cpp`](https://github.com/leejet/stable-diffusion.cpp)'s
//! `sd-server`; in the future a native bonsai-image server), polls its
//! `/health` endpoint until the model is loaded, and kills the child on
//! Drop.
//!
//! The implementation is intentionally a near-twin of [`crate::sidecar`]
//! for text — same spawn / health / kill contract, same Drop-kills-child
//! invariant, same env-override scheme. The differences are:
//!
//!   * default binary name is `sd-server`, default port is **13580** (one
//!     above the text sidecar's 13579) so the two never collide on
//!     loopback;
//!   * argv is built from [`ImageGenConfig`], not `RuntimeConfig`;
//!   * health budget allows much longer load times (image diffusion
//!     models take 5–30 s to memory-map and warm CUDA / Metal contexts).
//!
//! Group D Task 18 will move the default binary name + default port to
//! `ai_models.json` so a snapshot can ship a vendored binary path
//! without a code change.

use std::path::PathBuf;
use std::process::{Child, Command, Stdio};
use std::time::{Duration, Instant};

use thiserror::Error;

use super::transport::{ImageGenTransport, DEFAULT_IMAGE_GEN_REQUEST_TIMEOUT};

/// Env-var override for the image-gen server binary path. Used by
/// integration tests (`AEC_AI_IMAGE_BIN=/tmp/fake-sd`) and by the bridge
/// when the snapshot bundles a vendored binary. Empty value falls back to
/// [`DEFAULT_IMAGE_GEN_BIN`].
pub const IMAGE_GEN_BIN_ENV: &str = "AEC_AI_IMAGE_BIN";

/// Default binary name. The Phase 18 Group C decision is
/// `stable-diffusion.cpp`'s `sd-server` (leejet's pure-C++ port; no
/// Python, AGPL-compatible). Override via [`IMAGE_GEN_BIN_ENV`] when a
/// future native bonsai-image server ships.
pub const DEFAULT_IMAGE_GEN_BIN: &str = "sd-server";

/// Default loopback port for the image-gen sidecar. Picked one above
/// the text sidecar's 13579 so the two can run simultaneously on the
/// same machine without collision.
pub const DEFAULT_IMAGE_GEN_PORT: u16 = 13580;

/// Spawn configuration for the image-gen sidecar. Generated by the
/// bridge from the active model descriptor + per-machine governor
/// policy.
#[derive(Debug, Clone)]
pub struct ImageGenConfig {
    /// Loopback port the sidecar should bind. Defaults to
    /// [`DEFAULT_IMAGE_GEN_PORT`].
    pub port: u16,
    /// Absolute path to the diffusion model GGUF / safetensors file.
    /// Multi-file models (separate VAE / text encoder) live in the
    /// same directory and are referenced via [`Self::vae_path`].
    pub model_path: PathBuf,
    /// Optional path to a separate VAE. Many SD-family GGUFs embed
    /// the VAE; small Flux / SDXL-turbo distillations sometimes ship
    /// it as a sidecar `.safetensors`. None means "use the VAE
    /// embedded in the model file".
    pub vae_path: Option<PathBuf>,
    /// CPU threads for the diffusion sampler (only used when no GPU
    /// backend is available). The governor picks this based on host
    /// core count.
    pub threads: u32,
    /// Per-request HTTP timeout. Diffusion sampling is the dominant
    /// cost (30–180 s on commodity GPUs) so this is much larger than
    /// the text sidecar's request timeout. The Phase 18 Group C
    /// default is 180 s; the governor narrows it for low-tier hosts.
    pub request_timeout: Duration,
}

impl Default for ImageGenConfig {
    fn default() -> Self {
        Self {
            port: DEFAULT_IMAGE_GEN_PORT,
            model_path: PathBuf::new(),
            vae_path: None,
            threads: 4,
            request_timeout: DEFAULT_IMAGE_GEN_REQUEST_TIMEOUT,
        }
    }
}

#[derive(Debug, Error)]
pub enum ImageGenSpawnError {
    #[error("spawn `{bin}`: {source}")]
    Spawn {
        bin: String,
        #[source]
        source: std::io::Error,
    },
    #[error("image-gen sidecar did not become ready within {0:?}")]
    HealthTimeout(Duration),
    #[error("image-gen sidecar exited before becoming ready: {0:?}")]
    EarlyExit(Option<i32>),
    #[error("model path is empty — configure before spawning")]
    EmptyModelPath,
}

/// A live image-gen sidecar process. Killing the child on Drop is the
/// only correctness-critical invariant: the process holds the loopback
/// port and a multi-GiB mmap of the diffusion model, and leaking it
/// would prevent the next bridge instance from binding the same port
/// and would pin the model in RAM until reboot.
#[derive(Debug)]
pub struct ImageGenHandle {
    child: Option<Child>,
    transport: ImageGenTransport,
}

impl ImageGenHandle {
    pub fn transport(&self) -> &ImageGenTransport {
        &self.transport
    }

    /// Try to read the child's exit status without blocking. Returns
    /// `Some` only if the child has already exited; otherwise `None`.
    pub fn try_exit_code(&mut self) -> Option<i32> {
        let child = self.child.as_mut()?;
        child
            .try_wait()
            .ok()
            .flatten()
            .map(|status| status.code().unwrap_or(-1))
    }

    /// Explicit kill — equivalent to `drop(handle)` but lets the caller
    /// observe any I/O error (Drop swallows them).
    pub fn shutdown(mut self) {
        self.kill_inner();
    }

    fn kill_inner(&mut self) {
        if let Some(mut child) = self.child.take() {
            let _ = child.kill();
            let _ = child.wait();
        }
    }
}

impl Drop for ImageGenHandle {
    fn drop(&mut self) {
        self.kill_inner();
    }
}

/// Lookup the configured image-gen binary path, applying the
/// [`IMAGE_GEN_BIN_ENV`] override. Empty env value falls back to the
/// default (same shape as the text sidecar's `sidecar_bin`).
pub fn image_gen_bin() -> PathBuf {
    if let Ok(p) = std::env::var(IMAGE_GEN_BIN_ENV) {
        if !p.is_empty() {
            return PathBuf::from(p);
        }
    }
    PathBuf::from(DEFAULT_IMAGE_GEN_BIN)
}

/// Build the argv the image-gen binary expects. The shape targets
/// stable-diffusion.cpp's `sd-server` (leejet) — `--host`, `--port`,
/// `--model`, `--threads`, optional `--vae`. A future native
/// bonsai-image server is expected to accept the same flags (we will
/// adjust this function and the binary's argv contract together).
///
/// Returned as `Vec<String>` so tests can pin the exact argv shape
/// without re-running the binary lookup.
pub fn build_image_gen_spawn_args(config: &ImageGenConfig) -> Vec<String> {
    let mut args = vec![
        "--host".into(),
        "127.0.0.1".into(),
        "--port".into(),
        config.port.to_string(),
        "--model".into(),
        config.model_path.display().to_string(),
        "--threads".into(),
        config.threads.to_string(),
    ];
    if let Some(vae) = &config.vae_path {
        args.push("--vae".into());
        args.push(vae.display().to_string());
    }
    args
}

/// Spawn the image-gen sidecar and wait until its `/health` endpoint
/// reports ready.
///
/// `health_poll_timeout` is the overall budget — typically 60 s for a
/// cold-cache diffusion model load (much larger than the text
/// sidecar's 30 s because diffusion models warm CUDA / Metal contexts
/// in addition to mmap'ing the weights). The spawner polls every
/// 200 ms until the budget is exhausted.
///
/// The returned [`ImageGenHandle`] *owns* the child process; dropping
/// it kills the sidecar.
pub fn spawn(
    config: &ImageGenConfig,
    health_poll_timeout: Duration,
) -> Result<ImageGenHandle, ImageGenSpawnError> {
    if config.model_path.as_os_str().is_empty() {
        return Err(ImageGenSpawnError::EmptyModelPath);
    }
    let bin = image_gen_bin();
    let bin_display = bin.display().to_string();
    let mut cmd = Command::new(&bin);
    cmd.args(build_image_gen_spawn_args(config))
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    let child = cmd.spawn().map_err(|source| ImageGenSpawnError::Spawn {
        bin: bin_display,
        source,
    })?;
    let transport = ImageGenTransport::new(config.port, config.request_timeout);
    let mut handle = ImageGenHandle {
        child: Some(child),
        transport: transport.clone(),
    };
    poll_until_healthy(&transport, &mut handle, health_poll_timeout)?;
    Ok(handle)
}

/// Wrap a pre-existing image-gen sidecar process. Used by integration
/// tests that spin up a mock TCP server and want the runtime to treat
/// it as if it were a real sidecar. Caller is responsible for managing
/// the foreign process's lifecycle.
pub fn adopt(transport: ImageGenTransport) -> ImageGenHandle {
    ImageGenHandle {
        child: None,
        transport,
    }
}

fn poll_until_healthy(
    transport: &ImageGenTransport,
    handle: &mut ImageGenHandle,
    budget: Duration,
) -> Result<(), ImageGenSpawnError> {
    let start = Instant::now();
    // Slightly longer tick than the text sidecar (100 ms) — diffusion
    // model load is dominated by mmap + CUDA context init, neither of
    // which benefits from sub-200 ms health polling.
    let tick = Duration::from_millis(200);
    loop {
        if let Some(code) = handle.try_exit_code() {
            return Err(ImageGenSpawnError::EarlyExit(Some(code)));
        }
        if let Ok(true) = transport.health() {
            return Ok(());
        }
        if start.elapsed() >= budget {
            return Err(ImageGenSpawnError::HealthTimeout(budget));
        }
        std::thread::sleep(tick);
    }
}

/// Phase 18 Group D Task 21 — restart policy with exponential
/// backoff for the image-gen sidecar.
///
/// Mirrors [`crate::sidecar::RestartPolicy`] for the text sidecar
/// (same delay schedule, same `record_failure` / `next_delay` /
/// `reset` contract) but kept as a separate type so a future tuning
/// pass can dial the image-gen base / cap independently — image-gen
/// cold spawns are longer than text spawns (60 s vs 30 s budget),
/// so the failure semantics differ subtly (a 60 s `HealthTimeout`
/// might warrant a longer initial backoff than a 30 s text-side
/// timeout).
///
/// Delay schedule: each call to [`Self::record_failure`] first
/// bumps the consecutive-failure counter and then returns
/// `500 ms * 2^counter`, capped at the configured `max_delay`
/// (default 30 s). So the first failure returns 1 s, the second
/// 2 s, the third 4 s, etc. Reset on first success.
#[derive(Debug, Clone)]
pub struct ImageGenRestartPolicy {
    consecutive_failures: u32,
    max_delay: Duration,
}

impl Default for ImageGenRestartPolicy {
    fn default() -> Self {
        Self {
            consecutive_failures: 0,
            max_delay: Duration::from_secs(30),
        }
    }
}

impl ImageGenRestartPolicy {
    pub fn new(max_delay: Duration) -> Self {
        Self {
            consecutive_failures: 0,
            max_delay,
        }
    }

    /// Record a spawn failure. Returns the delay the caller should
    /// wait before the next attempt.
    pub fn record_failure(&mut self) -> Duration {
        self.consecutive_failures = self.consecutive_failures.saturating_add(1);
        self.next_delay()
    }

    /// Compute the delay for the current failure count without
    /// recording a new failure. Used by callers that want to
    /// inspect the policy before deciding whether to retry.
    pub fn next_delay(&self) -> Duration {
        let base_ms = 500_u64;
        let shift = self.consecutive_failures.min(20);
        let multiplier = 1u64.checked_shl(shift).unwrap_or(u64::MAX);
        let delay_ms = base_ms.saturating_mul(multiplier);
        Duration::from_millis(delay_ms).min(self.max_delay)
    }

    /// Reset after a successful spawn + health check.
    pub fn reset(&mut self) {
        self.consecutive_failures = 0;
    }

    pub fn consecutive_failures(&self) -> u32 {
        self.consecutive_failures
    }
}

/// Phase 18 Group D Task 21 — spawn the image-gen sidecar with
/// automatic retry. On failure, the [`ImageGenRestartPolicy`] is
/// advanced — `record_failure()` bumps the consecutive-failure
/// counter and returns the back-off duration to sleep before the
/// next attempt. Up to `max_attempts` total spawns are tried.
///
/// Returns the live handle on the first successful attempt. If all
/// attempts fail, returns the error from the **last** attempt — the
/// caller can inspect it with [`ImageGenSpawnError`].
///
/// Hard-stops on [`ImageGenSpawnError::EmptyModelPath`]: an empty
/// model path will never become non-empty by retrying, so retry
/// loops on this branch are wasteful. Every other error variant
/// (`Spawn`, `HealthTimeout`, `EarlyExit`) is potentially
/// transient (filesystem hiccup, slow CUDA init, OOM-kill of the
/// child) and is therefore retried.
pub fn spawn_with_retry(
    config: &ImageGenConfig,
    health_poll_timeout: Duration,
    policy: &mut ImageGenRestartPolicy,
    max_attempts: u32,
) -> Result<ImageGenHandle, ImageGenSpawnError> {
    if max_attempts == 0 {
        return Err(ImageGenSpawnError::HealthTimeout(health_poll_timeout));
    }
    let mut last_err: Option<ImageGenSpawnError> = None;
    let mut next_delay: Option<Duration> = None;
    for _ in 0..max_attempts {
        if let Some(delay) = next_delay.take() {
            std::thread::sleep(delay);
        }
        match spawn(config, health_poll_timeout) {
            Ok(handle) => {
                policy.reset();
                return Ok(handle);
            }
            Err(ImageGenSpawnError::EmptyModelPath) => {
                // Non-recoverable: no amount of retry will materialise
                // a model path. Surface the underlying error
                // immediately so the caller can fix the descriptor.
                return Err(ImageGenSpawnError::EmptyModelPath);
            }
            Err(e) => {
                // `record_failure` bumps the failure counter and
                // returns the exact delay to wait before the next
                // attempt, so the sleep above and the policy state
                // are always in lock-step.
                next_delay = Some(policy.record_failure());
                last_err = Some(e);
            }
        }
    }
    Err(last_err.unwrap_or(ImageGenSpawnError::HealthTimeout(health_poll_timeout)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    // Same process-global env-mutating test guard pattern as the text
    // sidecar — see `crate::sidecar::tests` for the rationale.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    struct EnvGuard {
        _lock: std::sync::MutexGuard<'static, ()>,
        prev: Option<String>,
    }

    impl EnvGuard {
        fn acquire() -> Self {
            let lock = ENV_LOCK
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner);
            let prev = std::env::var(IMAGE_GEN_BIN_ENV).ok();
            std::env::remove_var(IMAGE_GEN_BIN_ENV);
            Self { _lock: lock, prev }
        }
    }

    impl Drop for EnvGuard {
        fn drop(&mut self) {
            match self.prev.take() {
                Some(p) => std::env::set_var(IMAGE_GEN_BIN_ENV, p),
                None => std::env::remove_var(IMAGE_GEN_BIN_ENV),
            }
        }
    }

    #[test]
    fn image_gen_bin_honours_env_override() {
        let _g = EnvGuard::acquire();
        std::env::set_var(IMAGE_GEN_BIN_ENV, "/tmp/custom-sd-server");
        assert_eq!(image_gen_bin(), PathBuf::from("/tmp/custom-sd-server"));
        std::env::remove_var(IMAGE_GEN_BIN_ENV);
        assert_eq!(image_gen_bin(), PathBuf::from(DEFAULT_IMAGE_GEN_BIN));
    }

    #[test]
    fn empty_image_gen_env_var_falls_back_to_default() {
        let _g = EnvGuard::acquire();
        std::env::set_var(IMAGE_GEN_BIN_ENV, "");
        assert_eq!(image_gen_bin(), PathBuf::from(DEFAULT_IMAGE_GEN_BIN));
    }

    #[test]
    fn spawn_with_empty_model_path_reports_empty_model_path() {
        // No env mutation, but acquire the lock anyway so this test
        // does not race with the env-mutating ones in the same thread
        // pool (they would observe a stray default-path leak otherwise).
        let _g = EnvGuard::acquire();
        let cfg = ImageGenConfig::default();
        let result = spawn(&cfg, Duration::from_millis(10));
        assert!(matches!(result, Err(ImageGenSpawnError::EmptyModelPath)));
    }

    #[test]
    fn spawn_with_missing_binary_reports_spawn_error() {
        let _g = EnvGuard::acquire();
        std::env::set_var(
            IMAGE_GEN_BIN_ENV,
            "/nonexistent/aec-test-sd-server-image-gen",
        );
        let cfg = ImageGenConfig {
            model_path: PathBuf::from("/tmp/fake-model.gguf"),
            ..ImageGenConfig::default()
        };
        let result = spawn(&cfg, Duration::from_millis(10));
        assert!(matches!(result, Err(ImageGenSpawnError::Spawn { .. })));
    }

    #[test]
    fn build_spawn_args_emits_canonical_shape_without_vae() {
        let cfg = ImageGenConfig {
            port: 13580,
            model_path: PathBuf::from("/var/models/sd-image-gen/sd-turbo.gguf"),
            vae_path: None,
            threads: 8,
            request_timeout: Duration::from_secs(180),
        };
        let args = build_image_gen_spawn_args(&cfg);
        assert_eq!(
            args,
            vec![
                "--host".to_string(),
                "127.0.0.1".to_string(),
                "--port".to_string(),
                "13580".to_string(),
                "--model".to_string(),
                "/var/models/sd-image-gen/sd-turbo.gguf".to_string(),
                "--threads".to_string(),
                "8".to_string(),
            ]
        );
    }

    #[test]
    fn build_spawn_args_appends_vae_when_set() {
        let cfg = ImageGenConfig {
            port: 13580,
            model_path: PathBuf::from("/var/models/sd-image-gen/flux-schnell.gguf"),
            vae_path: Some(PathBuf::from(
                "/var/models/sd-image-gen/flux-vae.safetensors",
            )),
            threads: 4,
            request_timeout: Duration::from_secs(180),
        };
        let args = build_image_gen_spawn_args(&cfg);
        assert_eq!(
            args.last().unwrap(),
            "/var/models/sd-image-gen/flux-vae.safetensors"
        );
        let vae_flag_pos = args.iter().position(|a| a == "--vae").unwrap();
        // `--vae` is the *last* positional flag — appended after
        // `--threads`, so test the pair as a contiguous tail.
        assert_eq!(
            args[vae_flag_pos + 1],
            "/var/models/sd-image-gen/flux-vae.safetensors"
        );
    }

    #[test]
    fn default_image_gen_port_is_one_above_text() {
        // Pin the contract that text and image-gen sidecars do not
        // collide on loopback: text defaults to 13579 (in
        // `RuntimeConfig::default()`), image-gen to 13580. Tested as
        // hard literals so a future move of the text default into a
        // named constant doesn't silently break this invariant.
        assert_eq!(DEFAULT_IMAGE_GEN_PORT, 13580);
        let text_default = crate::runtime::RuntimeConfig::default().port;
        assert_eq!(text_default, 13579);
        assert_eq!(DEFAULT_IMAGE_GEN_PORT, text_default + 1);
    }

    // Phase 18 Group D Task 21 — exponential-backoff retry tests.

    #[test]
    fn image_gen_restart_policy_default_state_returns_base_delay() {
        // With zero consecutive failures, `next_delay` must return
        // the base (500 ms). `record_failure` increments first, so
        // the FIRST call to `record_failure` must return 1 s
        // (500 ms * 2^1).
        let mut policy = ImageGenRestartPolicy::default();
        assert_eq!(policy.consecutive_failures(), 0);
        assert_eq!(policy.next_delay(), Duration::from_millis(500));
        assert_eq!(policy.record_failure(), Duration::from_secs(1));
        assert_eq!(policy.consecutive_failures(), 1);
    }

    #[test]
    fn image_gen_restart_policy_doubles_until_max_delay_then_clamps() {
        // 500 ms × 2^n schedule, clamped at 30 s. Pin every step of
        // the schedule so a future tuning change cannot silently
        // alter the back-off curve.
        let mut policy = ImageGenRestartPolicy::default();
        let expected = [
            Duration::from_secs(1),  // 2^1 * 500ms
            Duration::from_secs(2),  // 2^2 * 500ms
            Duration::from_secs(4),  // 2^3 * 500ms
            Duration::from_secs(8),  // 2^4 * 500ms
            Duration::from_secs(16), // 2^5 * 500ms
            Duration::from_secs(30), // 2^6 * 500ms = 32s, clamped to 30s
            Duration::from_secs(30), // clamp holds
            Duration::from_secs(30), // clamp holds
        ];
        for (i, want) in expected.iter().enumerate() {
            let got = policy.record_failure();
            assert_eq!(
                got,
                *want,
                "step {i}: failure #{} returned {got:?}, expected {want:?}",
                i + 1
            );
        }
    }

    #[test]
    fn image_gen_restart_policy_reset_clears_failure_count() {
        let mut policy = ImageGenRestartPolicy::default();
        policy.record_failure();
        policy.record_failure();
        policy.record_failure();
        assert_eq!(policy.consecutive_failures(), 3);
        policy.reset();
        assert_eq!(policy.consecutive_failures(), 0);
        // Post-reset, the next failure should return the same value
        // as the first-ever failure (1 s).
        assert_eq!(policy.record_failure(), Duration::from_secs(1));
    }

    #[test]
    fn image_gen_restart_policy_saturates_under_extreme_failure_count() {
        // Defense-in-depth: extreme failure counts (e.g. unbounded
        // sidecar loop) must not overflow the shift or the
        // millisecond multiplication. `consecutive_failures.min(20)`
        // bounds the shift; `saturating_mul` is just belt-and-
        // braces. The final delay is clamped at `max_delay`.
        let mut policy = ImageGenRestartPolicy::default();
        for _ in 0..100 {
            policy.record_failure();
        }
        assert_eq!(policy.consecutive_failures(), 100);
        // After many failures, the schedule is at its hard ceiling.
        assert_eq!(policy.next_delay(), Duration::from_secs(30));
    }

    #[test]
    fn spawn_with_retry_short_circuits_on_empty_model_path() {
        // `EmptyModelPath` is non-recoverable: no retry will ever
        // materialise a non-empty model path, and the retry loop
        // would be a multi-second waste of latency. The retry
        // helper must short-circuit on this error without
        // advancing the policy or sleeping.
        let _g = EnvGuard::acquire();
        let mut policy = ImageGenRestartPolicy::default();
        let cfg = ImageGenConfig::default();
        let start = std::time::Instant::now();
        let result = spawn_with_retry(&cfg, Duration::from_millis(1), &mut policy, 5);
        assert!(
            matches!(result, Err(ImageGenSpawnError::EmptyModelPath)),
            "expected EmptyModelPath, got {result:?}"
        );
        assert_eq!(
            policy.consecutive_failures(),
            0,
            "EmptyModelPath must not advance the policy",
        );
        // Pin that we did NOT sleep through 5 retries (each retry
        // would sleep at least 1 s) — fast-fail.
        assert!(
            start.elapsed() < Duration::from_millis(500),
            "EmptyModelPath fast-fail must be < 500 ms, took {:?}",
            start.elapsed(),
        );
    }

    #[test]
    fn spawn_with_retry_retries_on_spawn_failure_until_attempt_budget_exhausted() {
        // Wire a non-existent binary so every spawn attempt fails
        // with `Spawn { source: NotFound }`. Use `max_delay = 1ms`
        // to keep this test fast (otherwise the back-off would dominate).
        let _g = EnvGuard::acquire();
        std::env::set_var(
            IMAGE_GEN_BIN_ENV,
            "/nonexistent/aec-test-sd-server-image-gen-retry",
        );
        let mut policy = ImageGenRestartPolicy::new(Duration::from_millis(1));
        let cfg = ImageGenConfig {
            model_path: PathBuf::from("/tmp/fake-model.gguf"),
            ..ImageGenConfig::default()
        };
        let result = spawn_with_retry(&cfg, Duration::from_millis(1), &mut policy, 3);
        assert!(
            matches!(result, Err(ImageGenSpawnError::Spawn { .. })),
            "expected Spawn error, got {result:?}"
        );
        assert_eq!(
            policy.consecutive_failures(),
            3,
            "each of the 3 attempts must advance the policy",
        );
    }

    #[test]
    fn spawn_with_retry_zero_max_attempts_returns_health_timeout() {
        // Defense-in-depth: a `max_attempts == 0` config (which the
        // call sites should never construct) must not panic and
        // must return a deterministic error so the caller can log /
        // surface it. We pin `HealthTimeout` so the caller has a
        // stable variant to match against.
        let _g = EnvGuard::acquire();
        let mut policy = ImageGenRestartPolicy::default();
        let cfg = ImageGenConfig {
            model_path: PathBuf::from("/tmp/fake-model.gguf"),
            ..ImageGenConfig::default()
        };
        let result = spawn_with_retry(&cfg, Duration::from_millis(1), &mut policy, 0);
        assert!(
            matches!(result, Err(ImageGenSpawnError::HealthTimeout(_))),
            "expected HealthTimeout for max_attempts=0, got {result:?}"
        );
        assert_eq!(policy.consecutive_failures(), 0);
    }
}
